apiVersion: v1
kind: Service
metadata:
  name: django-notes-service
  namespace: django-notes
spec:
  type: NodePort
  selector:
    app: django-notes
    ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
